apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::535002850032:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-4biFO4fW0ut8
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::535002850032:user/manisha
      username: manisha    
kind: ConfigMap
metadata:
  creationTimestamp: "2025-06-08T05:59:54Z"
  name: aws-auth
  namespace: kube-system
  uid: 8d1bf9fc-f599-488d-b9e4-859b134fa7c2